# Generated by Django 4.0.2 on 2022-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_balance_alter_user_id_listing_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='base_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./templates/auctions/images/'),
        ),
    ]
