# Generated by Django 4.0.2 on 2022-03-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_base_price_listing_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./auctions/templates/auctions/images'),
        ),
    ]
