# Generated by Django 4.0.2 on 2022-03-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_items', to='auctions.listing'),
        ),
    ]
