# Generated by Django 4.0.2 on 2022-03-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='General', max_length=64),
        ),
    ]
