# Generated by Django 4.0.2 on 2022-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_comments_commenter_alter_comments_listed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
