# Generated by Django 4.0.2 on 2022-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='first',
            field=models.CharField(default='Jane', max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last',
            field=models.CharField(default='Doe', max_length=64),
        ),
    ]
